# Form implementation generated from reading ui file 'product_add_edit.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(488, 794)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.articul_input = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.articul_input.setFont(font)
        self.articul_input.setStyleSheet("#articul_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#articul_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.articul_input.setReadOnly(False)
        self.articul_input.setObjectName("articul_input")
        self.gridLayout.addWidget(self.articul_input, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.photo = QtWidgets.QLabel(parent=Dialog)
        self.photo.setMaximumSize(QtCore.QSize(70, 70))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../../../../Users/nightmare/Downloads/import/picture.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.gridLayout.addWidget(self.photo, 3, 0, 1, 1)
        self.download_photo = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_photo.sizePolicy().hasHeightForWidth())
        self.download_photo.setSizePolicy(sizePolicy)
        self.download_photo.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.download_photo.setFont(font)
        self.download_photo.setStyleSheet("#download_photo {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#download_photo:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.download_photo.setObjectName("download_photo")
        self.gridLayout.addWidget(self.download_photo, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.name_input = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.name_input.setFont(font)
        self.name_input.setStyleSheet("#name_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#name_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.name_input.setPlaceholderText("")
        self.name_input.setObjectName("name_input")
        self.gridLayout.addWidget(self.name_input, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.category_input = QtWidgets.QComboBox(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.category_input.setFont(font)
        self.category_input.setStyleSheet("#category_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#category_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.category_input.setObjectName("category_input")
        self.category_input.addItem("")
        self.category_input.addItem("")
        self.gridLayout.addWidget(self.category_input, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.description_input = QtWidgets.QTextEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.description_input.setFont(font)
        self.description_input.setStyleSheet("#description_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#description_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.description_input.setObjectName("description_input")
        self.gridLayout.addWidget(self.description_input, 10, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 1)
        self.maker_input = QtWidgets.QComboBox(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.maker_input.setFont(font)
        self.maker_input.setStyleSheet("#maker_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#maker_input:hover {\n"
"    border-color: #00FA9A;\n"
"}")
        self.maker_input.setObjectName("maker_input")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.maker_input.addItem("")
        self.gridLayout.addWidget(self.maker_input, 12, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 13, 0, 1, 1)
        self.provider_input = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.provider_input.setFont(font)
        self.provider_input.setStyleSheet("#provider_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#provider_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.provider_input.setObjectName("provider_input")
        self.gridLayout.addWidget(self.provider_input, 14, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 15, 0, 1, 1)
        self.price_input = QtWidgets.QLineEdit(parent=Dialog)
        self.price_input.setObjectName("price_input")
        self.gridLayout.addWidget(self.price_input, 16, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 17, 0, 1, 1)
        self.metric_input = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.metric_input.setFont(font)
        self.metric_input.setStyleSheet("#metric_input {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#metric_input:focus {\n"
"    border-color: #00FA9A;\n"
"}")
        self.metric_input.setObjectName("metric_input")
        self.gridLayout.addWidget(self.metric_input, 18, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 19, 0, 1, 1)
        self.quantity_input = QtWidgets.QLineEdit(parent=Dialog)
        self.quantity_input.setObjectName("quantity_input")
        self.gridLayout.addWidget(self.quantity_input, 20, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 21, 0, 1, 1)
        self.discount_input = QtWidgets.QLineEdit(parent=Dialog)
        self.discount_input.setObjectName("discount_input")
        self.gridLayout.addWidget(self.discount_input, 22, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 23, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("#save_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#save_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 24, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("#cancel_button {\n"
"    background-color: #7FFF00;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#cancel_button:hover {\n"
"    background-color: #00FA9A;\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 25, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Артикул:"))
        self.label.setText(_translate("Dialog", "Фото:"))
        self.download_photo.setText(_translate("Dialog", "Загрузить фото"))
        self.label_4.setText(_translate("Dialog", "Наименование:"))
        self.label_5.setText(_translate("Dialog", "Категория:"))
        self.category_input.setItemText(0, _translate("Dialog", "Женская обувь"))
        self.category_input.setItemText(1, _translate("Dialog", "Мужская обувь"))
        self.label_6.setText(_translate("Dialog", "Описание:"))
        self.label_7.setText(_translate("Dialog", "Производитель:"))
        self.maker_input.setItemText(0, _translate("Dialog", "Kari"))
        self.maker_input.setItemText(1, _translate("Dialog", "Marco Tozzi"))
        self.maker_input.setItemText(2, _translate("Dialog", "Рос"))
        self.maker_input.setItemText(3, _translate("Dialog", "Rieker"))
        self.maker_input.setItemText(4, _translate("Dialog", "Alessio Nesca"))
        self.maker_input.setItemText(5, _translate("Dialog", "CROSBY"))
        self.maker_input.setItemText(6, _translate("Dialog", "New Item"))
        self.label_8.setText(_translate("Dialog", "Поставщик:"))
        self.label_9.setText(_translate("Dialog", "Цена"))
        self.label_10.setText(_translate("Dialog", "Ед. измерения:"))
        self.label_11.setText(_translate("Dialog", "Количество:"))
        self.label_12.setText(_translate("Dialog", "Скидка (%):"))
        self.save_button.setText(_translate("Dialog", "Сохранить"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
