# Form implementation generated from reading ui file 'product_list_administrator.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ProductListAdministratorWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 772)
        MainWindow.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exit_product_list = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_product_list.setMinimumSize(QtCore.QSize(100, 50))
        self.exit_product_list.setMaximumSize(QtCore.QSize(100, 50))
        self.exit_product_list.setStyleSheet("QPushButton#exit_product_list{\n"
"    border: 1px solid #000; \n"
"    background-color:#7FFF00;\n"
"}\n"
"QPushButton#exit_product_list:hover {\n"
"    background-color:#00FA9A;\n"
"}")
        self.exit_product_list.setObjectName("exit_product_list")
        self.horizontalLayout_3.addWidget(self.exit_product_list)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.orders = QtWidgets.QPushButton(parent=self.centralwidget)
        self.orders.setMinimumSize(QtCore.QSize(200, 0))
        self.orders.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.orders.setFont(font)
        self.orders.setStyleSheet("QPushButton#orders{\n"
"    border: 1px solid #000; \n"
"    background-color:#7FFF00;\n"
"}\n"
"QPushButton#orders:hover {\n"
"    background-color:#00FA9A;\n"
"}")
        self.orders.setObjectName("orders")
        self.horizontalLayout_3.addWidget(self.orders)
        self.remove_product = QtWidgets.QPushButton(parent=self.centralwidget)
        self.remove_product.setMinimumSize(QtCore.QSize(250, 0))
        self.remove_product.setMaximumSize(QtCore.QSize(250, 50))
        self.remove_product.setStyleSheet("QPushButton#remove_product{\n"
"    border: 1px solid #000; \n"
"    background-color:#7FFF00;\n"
"}\n"
"QPushButton#remove_product:hover {\n"
"    background-color:#00FA9A;\n"
"}")
        self.remove_product.setObjectName("remove_product")
        self.horizontalLayout_3.addWidget(self.remove_product)
        self.add_product = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_product.setMinimumSize(QtCore.QSize(250, 0))
        self.add_product.setMaximumSize(QtCore.QSize(250, 50))
        self.add_product.setStyleSheet("QPushButton#add_product{\n"
"    border: 1px solid #000; \n"
"    background-color:#7FFF00;\n"
"}\n"
"QPushButton#add_product:hover {\n"
"    background-color:#00FA9A;\n"
"}")
        self.add_product.setObjectName("add_product")
        self.horizontalLayout_3.addWidget(self.add_product)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(60, 50))
        self.label_3.setMaximumSize(QtCore.QSize(60, 50))
        self.label_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images//Icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.search.setFont(font)
        self.search.setStyleSheet("QLineEdit#search{\n"
"    border: 1px solid #000; \n"
"}\n"
"QLineEdit#search:focus {\n"
"    border: 1px solid#00FA9A;\n"
"}")
        self.search.setText("")
        self.search.setFrame(True)
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dillers = QtWidgets.QComboBox(parent=self.centralwidget)
        self.dillers.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.dillers.setFont(font)
        self.dillers.setStyleSheet("QComboBox#dillers{\n"
"    border: 1px solid #000; \n"
"}\n"
"QComboBox#dillers:focus {\n"
"    border: 1px solid#00FA9A;\n"
"}")
        self.dillers.setObjectName("dillers")
        self.dillers.addItem("")
        self.horizontalLayout.addWidget(self.dillers)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.storage = QtWidgets.QComboBox(parent=self.centralwidget)
        self.storage.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.storage.setFont(font)
        self.storage.setStyleSheet("QComboBox#storage{\n"
"    border: 1px solid #000; \n"
"}\n"
"QComboBox#storage:focus {\n"
"    border: 1px solid#00FA9A;\n"
"}")
        self.storage.setObjectName("storage")
        self.storage.addItem("")
        self.storage.addItem("")
        self.horizontalLayout.addWidget(self.storage)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1043, 604))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.product_layout_5 = QtWidgets.QHBoxLayout()
        self.product_layout_5.setObjectName("product_layout_5")
        self.product_photo_layout_5 = QtWidgets.QGridLayout()
        self.product_photo_layout_5.setObjectName("product_photo_layout_5")
        self.product_photo = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_photo.sizePolicy().hasHeightForWidth())
        self.product_photo.setSizePolicy(sizePolicy)
        self.product_photo.setMinimumSize(QtCore.QSize(200, 200))
        self.product_photo.setMaximumSize(QtCore.QSize(200, 200))
        self.product_photo.setStyleSheet("QLabel#product_photo{\n"
"    border: 1px solid #000; \n"
"}\n"
"QLabel#product_photo:hover {\n"
"    border: 2px solid #00FA9A;\n"
"}")
        self.product_photo.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.product_photo.setText("")
        self.product_photo.setPixmap(QtGui.QPixmap("import/6.jpg"))
        self.product_photo.setScaledContents(True)
        self.product_photo.setObjectName("product_photo")
        self.product_photo_layout_5.addWidget(self.product_photo, 0, 0, 1, 1)
        self.product_layout_5.addLayout(self.product_photo_layout_5)
        self.sale_layout_5 = QtWidgets.QGridLayout()
        self.sale_layout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.sale_layout_5.setObjectName("sale_layout_5")
        self.sale_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sale_5.sizePolicy().hasHeightForWidth())
        self.sale_5.setSizePolicy(sizePolicy)
        self.sale_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.sale_5.setStyleSheet("QLabel#sale_5{\n"
"    border: 1px solid #000; \n"
"    background-color:#7FFF00\n"
"}\n"
"QLabel#sale_5:hover {\n"
"    border: 2px solid #00FA9A;\n"
"}")
        self.sale_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.sale_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sale_5.setObjectName("sale_5")
        self.sale_layout_5.addWidget(self.sale_5, 1, 1, 1, 1)
        self.widget_product = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_product.setStyleSheet("QWidget#widget_product {\n"
"    border: 1px solid #000; \n"
"}\n"
"QWidget#widget_product:hover {\n"
"    border: 2px solid #00FA9A;\n"
"}")
        self.widget_product.setObjectName("widget_product")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_product)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.product_info_layout_5 = QtWidgets.QVBoxLayout()
        self.product_info_layout_5.setObjectName("product_info_layout_5")
        self.category_n_name_5 = QtWidgets.QLabel(parent=self.widget_product)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category_n_name_5.sizePolicy().hasHeightForWidth())
        self.category_n_name_5.setSizePolicy(sizePolicy)
        self.category_n_name_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.category_n_name_5.setObjectName("category_n_name_5")
        self.product_info_layout_5.addWidget(self.category_n_name_5)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.description_5 = QtWidgets.QLabel(parent=self.widget_product)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_5.sizePolicy().hasHeightForWidth())
        self.description_5.setSizePolicy(sizePolicy)
        self.description_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.description_5.setObjectName("description_5")
        self.horizontalLayout_21.addWidget(self.description_5)
        self.product_info_layout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.creator_5 = QtWidgets.QLabel(parent=self.widget_product)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.creator_5.sizePolicy().hasHeightForWidth())
        self.creator_5.setSizePolicy(sizePolicy)
        self.creator_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.creator_5.setObjectName("creator_5")
        self.horizontalLayout_22.addWidget(self.creator_5)
        self.product_info_layout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.provider_5 = QtWidgets.QLabel(parent=self.widget_product)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.provider_5.sizePolicy().hasHeightForWidth())
        self.provider_5.setSizePolicy(sizePolicy)
        self.provider_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.provider_5.setObjectName("provider_5")
        self.horizontalLayout_23.addWidget(self.provider_5)
        self.product_info_layout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.price_5 = QtWidgets.QLabel(parent=self.widget_product)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_5.sizePolicy().hasHeightForWidth())
        self.price_5.setSizePolicy(sizePolicy)
        self.price_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.price_5.setObjectName("price_5")
        self.horizontalLayout_24.addWidget(self.price_5)
        self.product_info_layout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.metric_5 = QtWidgets.QLabel(parent=self.widget_product)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metric_5.sizePolicy().hasHeightForWidth())
        self.metric_5.setSizePolicy(sizePolicy)
        self.metric_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.metric_5.setObjectName("metric_5")
        self.horizontalLayout_25.addWidget(self.metric_5)
        self.product_info_layout_5.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.quantity_5 = QtWidgets.QLabel(parent=self.widget_product)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantity_5.sizePolicy().hasHeightForWidth())
        self.quantity_5.setSizePolicy(sizePolicy)
        self.quantity_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.quantity_5.setObjectName("quantity_5")
        self.horizontalLayout_26.addWidget(self.quantity_5)
        self.product_info_layout_5.addLayout(self.horizontalLayout_26)
        self.verticalLayout_2.addLayout(self.product_info_layout_5)
        self.sale_layout_5.addWidget(self.widget_product, 1, 0, 1, 1)
        self.product_layout_5.addLayout(self.sale_layout_5)
        self.product_layout_5.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.product_layout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_product_list.setText(_translate("MainWindow", "Выход"))
        self.orders.setText(_translate("MainWindow", "Заказы"))
        self.remove_product.setText(_translate("MainWindow", "Удалить товар"))
        self.add_product.setText(_translate("MainWindow", "Добавить товар"))
        self.search.setPlaceholderText(_translate("MainWindow", "Поиск"))
        self.label.setText(_translate("MainWindow", "Поставщик:"))
        self.dillers.setToolTip(_translate("MainWindow", "<html><head/><body><p>Все поставщики</p><p><br/></p></body></html>"))
        self.dillers.setItemText(0, _translate("MainWindow", "Все поставщики"))
        self.label_4.setText(_translate("MainWindow", "Количество на складе:"))
        self.storage.setItemText(0, _translate("MainWindow", "Больше"))
        self.storage.setItemText(1, _translate("MainWindow", "Меньше"))
        self.label_2.setText(_translate("MainWindow", "Фамилия Имя Отчество"))
        self.sale_5.setText(_translate("MainWindow", "Действущая скидка"))
        self.category_n_name_5.setText(_translate("MainWindow", "Категория товара | Наименование товара"))
        self.description_5.setText(_translate("MainWindow", "Описание товара: *описание*"))
        self.creator_5.setText(_translate("MainWindow", "Производитель: *производитель*"))
        self.provider_5.setText(_translate("MainWindow", "Поставщик: *поставщик*"))
        self.price_5.setText(_translate("MainWindow", "Цена: *цена*"))
        self.metric_5.setText(_translate("MainWindow", "Единица измерения: *шт*"))
        self.quantity_5.setText(_translate("MainWindow", "Количество на складе: *кол-во*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ProductListAdministratorWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
