# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Test(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(446, 370)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.positive = QtWidgets.QPushButton(parent=Form)
        self.positive.setMinimumSize(QtCore.QSize(0, 50))
        self.positive.setObjectName("positive")
        self.gridLayout_2.addWidget(self.positive, 0, 0, 1, 1)
        self.negative = QtWidgets.QPushButton(parent=Form)
        self.negative.setMinimumSize(QtCore.QSize(0, 50))
        self.negative.setObjectName("negative")
        self.gridLayout_2.addWidget(self.negative, 1, 0, 1, 1)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.positive.setText(_translate("Form", "Позитивный тест"))
        self.negative.setText(_translate("Form", "Негативный тест"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Test()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
